// Tiny OpenAI-compatible stub for deterministic e2e AI generation.
// Answers any POST to a /chat/completions path with a fixed JSON email payload.
import http from "http";

const PORT = Number(process.env.AI_STUB_PORT ?? 9899);

const completion = {
  id: "cmpl-e2e-stub",
  object: "chat.completion",
  choices: [
    {
      index: 0,
      message: {
        role: "assistant",
        content: JSON.stringify({
          subject: "E2E Stub Subject",
          body: "Hola,\n\nEste es un email generado por el stub de pruebas.\n\nSaludos",
          personalizationNotes: "Generated by the e2e AI stub",
        }),
      },
      finish_reason: "stop",
    },
  ],
  usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 },
};

const server = http.createServer((req, res) => {
  if (req.method === "POST" && req.url?.includes("/chat/completions")) {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify(completion));
    return;
  }
  res.writeHead(200, { "content-type": "application/json" });
  res.end(JSON.stringify({ ok: true }));
});

server.listen(PORT, () => {
  console.log(`AI stub listening on http://localhost:${PORT}`);
});
