import { Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FilterBar } from "@/components/shared/filter-bar";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function CampaignsFilterBar({ search, status, perPage, selectedCount, onSearchChange, onStatusChange, onPerPageChange, onDeleteSelected }: { search: string; status: string; perPage: number; selectedCount: number; onSearchChange: (value: string) => void; onStatusChange: (value: string) => void; onPerPageChange: (value: number) => void; onDeleteSelected: () => void }) {
  return <div className="sticky top-0 z-10 border-b bg-background px-6 py-3"><FilterBar><Input placeholder="Search campaigns…" value={search} onChange={(event) => onSearchChange(event.target.value)} className="min-w-[220px] flex-1" /><Select value={status} onValueChange={onStatusChange}><SelectTrigger className="w-[180px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All Statuses</SelectItem><SelectItem value="generating">Generating</SelectItem><SelectItem value="pending_review">Pending Review</SelectItem><SelectItem value="ready_to_send">Ready to Send</SelectItem><SelectItem value="sending">Sending</SelectItem><SelectItem value="paused">Paused</SelectItem><SelectItem value="completed">Completed</SelectItem><SelectItem value="failed">Failed</SelectItem></SelectContent></Select><Select value={String(perPage)} onValueChange={(value) => onPerPageChange(Number(value))}><SelectTrigger className="w-[110px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="25">25 / page</SelectItem><SelectItem value="50">50 / page</SelectItem><SelectItem value="100">100 / page</SelectItem></SelectContent></Select>{selectedCount > 0 && <Button variant="danger" size="sm" onClick={onDeleteSelected}><Trash2 className="h-3.5 w-3.5" />Delete Selected ({selectedCount})</Button>}</FilterBar></div>;
}
