import Link from "next/link";
import { Copy, FilePen, MoreHorizontal, Pencil, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { StatusBadge } from "@/components/shared/status-badge";
import { formatDate } from "@/lib/utils";
import type { CampaignRow } from "./campaign-list-types";

export function CampaignsTable({ campaigns, selectedIds, onToggleAll, onToggleSelect, onRename, onDuplicate, duplicatingId, onDelete }: { campaigns: CampaignRow[]; selectedIds: Set<string>; onToggleAll: () => void; onToggleSelect: (id: string) => void; onRename: (campaign: CampaignRow) => void; onDuplicate: (campaign: CampaignRow) => void; duplicatingId: string | null; onDelete: (id: string) => void }) {
  return <Table><TableHeader><TableRow><TableHead className="w-10"><Checkbox checked={campaigns.length > 0 && campaigns.every((campaign) => selectedIds.has(campaign.id))} onCheckedChange={onToggleAll} /></TableHead><TableHead>Campaign</TableHead><TableHead>List</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Total</TableHead><TableHead className="text-right">Sent</TableHead><TableHead className="text-right">Failed</TableHead><TableHead className="text-right">Pending</TableHead><TableHead>Created</TableHead><TableHead>Last Sent</TableHead><TableHead className="w-16 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{campaigns.length === 0 ? <TableRow><TableCell colSpan={11} className="py-12 text-center text-sm text-muted-foreground">No campaigns match your filters.</TableCell></TableRow> : campaigns.map((campaign) => <CampaignTableRow key={campaign.id} campaign={campaign} selected={selectedIds.has(campaign.id)} onToggleSelect={onToggleSelect} onRename={onRename} onDuplicate={onDuplicate} duplicating={duplicatingId === campaign.id} onDelete={onDelete} />)}</TableBody></Table>;
}

function CampaignTableRow({ campaign, selected, onToggleSelect, onRename, onDuplicate, duplicating, onDelete }: { campaign: CampaignRow; selected: boolean; onToggleSelect: (id: string) => void; onRename: (campaign: CampaignRow) => void; onDuplicate: (campaign: CampaignRow) => void; duplicating: boolean; onDelete: (id: string) => void }) {
  return <TableRow><TableCell><Checkbox checked={selected} onCheckedChange={() => onToggleSelect(campaign.id)} /></TableCell><TableCell><Link href={`/campaigns/${campaign.id}`} className="font-medium text-foreground transition-colors hover:text-primary">{campaign.name}</Link></TableCell><TableCell><Link href={`/lists/${campaign.list.id}`} className="text-sm text-muted-foreground transition-colors hover:text-primary">{campaign.list.name}</Link></TableCell><TableCell><StatusBadge status={campaign.status} /></TableCell><TableCell className="text-right tabular-nums">{campaign.totalEmails}</TableCell><TableCell className="text-right tabular-nums font-medium text-emerald-700">{campaign.sentCount}</TableCell><TableCell className="text-right tabular-nums text-destructive">{campaign.failedCount > 0 ? campaign.failedCount : "—"}</TableCell><TableCell className="text-right tabular-nums text-muted-foreground">{campaign.approvalPendingCount > 0 ? campaign.approvalPendingCount : "—"}</TableCell><TableCell className="text-sm text-muted-foreground">{formatDate(campaign.createdAt)}</TableCell><TableCell className="text-sm text-muted-foreground">{campaign.completedAt ? formatDate(campaign.completedAt) : "—"}</TableCell><TableCell className="text-right"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="sm" className="h-7 w-7 p-0"><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link href={`/campaigns/${campaign.id}`}><Pencil className="mr-2 h-3.5 w-3.5" />Edit</Link></DropdownMenuItem><DropdownMenuItem onClick={() => onRename(campaign)}><FilePen className="mr-2 h-3.5 w-3.5" />Rename</DropdownMenuItem><DropdownMenuItem onClick={() => onDuplicate(campaign)} disabled={duplicating}><Copy className="mr-2 h-3.5 w-3.5" />{duplicating ? "Duplicating…" : "Duplicate"}</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem className="text-destructive focus:text-destructive" onClick={() => onDelete(campaign.id)}><Trash2 className="mr-2 h-3.5 w-3.5" />Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>;
}
