import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "@/hooks/use-toast";
import type { CampaignRow } from "./campaign-list-types";

export function useCampaignListActions(selectedIds: Set<string>, clearSelection: () => void) {
  const queryClient = useQueryClient(); const [showBulkDeleteConfirm, setShowBulkDeleteConfirm] = useState(false); const [deletingId, setDeletingId] = useState<string | null>(null); const [renameId, setRenameId] = useState<string | null>(null); const [renameName, setRenameName] = useState(""); const [duplicatingId, setDuplicatingId] = useState<string | null>(null); const invalidate = () => queryClient.invalidateQueries({ queryKey: ["campaigns"] });
  const deleteSelected = async () => { const count = selectedIds.size; await Promise.all([...selectedIds].map((id) => fetch(`/api/campaigns/${id}`, { method: "DELETE" }))); toast.success(`${count} campaign${count === 1 ? "" : "s"} deleted`, "They have been permanently removed."); clearSelection(); setShowBulkDeleteConfirm(false); invalidate(); };
  const deleteCampaign = async () => { if (!deletingId) return; await fetch(`/api/campaigns/${deletingId}`, { method: "DELETE" }); toast.success("Campaign deleted", "The campaign has been permanently removed."); setDeletingId(null); invalidate(); };
  const renameCampaign = async () => { if (!renameId || !renameName.trim()) return; const response = await fetch(`/api/campaigns/${renameId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: renameName.trim() }) }); if (response.ok) { toast.success("Campaign renamed", "The campaign name has been updated."); setRenameId(null); setRenameName(""); invalidate(); } else { const error = await response.json(); toast.error("Rename failed", error.error ?? "Could not rename the campaign."); } };
  const duplicateCampaign = async (campaign: CampaignRow) => { setDuplicatingId(campaign.id); try { const response = await fetch("/api/campaigns", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: `Copy of ${campaign.name}`, listId: campaign.list.id, goal: campaign.goal ?? undefined, product: campaign.product ?? undefined, cta: campaign.cta ?? undefined, tone: campaign.tone ?? undefined, language: campaign.language, emailLength: campaign.emailLength, systemPrompt: campaign.systemPrompt ?? "", intervalType: campaign.intervalType, minInterval: campaign.minInterval, maxInterval: campaign.maxInterval, dailyLimit: campaign.dailyLimit, hourlyLimit: campaign.hourlyLimit, aiProvider: campaign.aiProvider ?? undefined, aiModel: campaign.aiModel ?? undefined }) }); if (response.ok) { toast.success("Campaign duplicated", `"Copy of ${campaign.name}" has been created.`); invalidate(); } else { const error = await response.json(); toast.error("Duplicate failed", error.error ?? "Could not duplicate the campaign."); } } finally { setDuplicatingId(null); } };
  const startRename = (campaign: CampaignRow) => { setRenameId(campaign.id); setRenameName(campaign.name); }; const closeRename = () => { setRenameId(null); setRenameName(""); };
  return { showBulkDeleteConfirm, setShowBulkDeleteConfirm, deletingId, setDeletingId, renameId, renameName, setRenameName, duplicatingId, deleteSelected, deleteCampaign, renameCampaign, duplicateCampaign, startRename, closeRename };
}
